---
format:
  html:
    toc: false
    number-sections: false
---

# Methods  {#methods}

This section describes the process, considerations, and tools that went into developing each visualization in the Home tab. All the code for this project is available on [GitHub](https://github.com/anly503/spring2023-project-team-4/tree/main/code).


### Figure 1: Table of US bank assets, equity and liabilities per state of of 2022Q4
[View plot](index.qmd#sec-interactive-table)

The interactive table was built with the quarterly financials data set collected with the API client we built. We first selected rows with December 31st, 2022, as their filing date, and then we aggregated them by equities, liabilities, and assets. Next, we performed formatting on the numbers format and colors and then created a figure that aggregated the three tables. A drop-down was also added, which changes the display of the financial metrics selected.


### Figure 2: Grid bubble map of the progression of bank assets per decade per state 
[View plot](index.qmd#sec-grid-bubble-map)

This plot is constructed using the `Folium` and `Geopandas` Python libraries and uses the quarterly financial data. We then combined this data with the ZIP code coordinate data to estimate the bank's location. This join procedure added latitude and longitude columns to the data set, which we then combined into a two-tuple named `zip_coordinates`.

To produce the plots, we first converted the data into a Geodataframe. Next, we created a function named. `plot_bank_assets_by_date()`, that filters the Geodataframe by date and then groups by state. Then, the function creates a `Folium` map and plots the bubbles. The function is run four times for December 31st of 1992, 2002, 2012, and 2022. The resulting plots are organized into a 2 x 2 grid and rendered as HTML. The end product is a grid of `Folium` plots that allow the user to see the progression of the growth of bank assets in each decade and fully interact with each of these maps.

Alternative attempts to produce this plot included cluster markers which failed to capture the size of the banks' assets, rather than just the count. Additionally, we set up a date slider with a play button, which did not allow for an immersive visual experience due to the plot `Folium` plot having to re-render each time. Future versions of this plot may include server-side action that allows for this kind of functionality.

### Figure 3: Dot map with heatmap overlay of bank assets as of Q4 2022
[View plot](index.qmd#sec-dot-and-heatmap)

This second geospatial plot follows a similar logic to the previous; however, it only shows data as of December 31st, 2022. The main difference is that it shows a point in the ZIP code where each bank is. The plot also has a heatmap overlay showing the concentration of banks in the U.S. map. This plot also uses bubble size to show the size of the banks' assets, in which the largest banks in the U.S. distinguish themselves clearly.

### Figure 4: State bank deposits by bank
[View plot](index.qmd#sec-state-bank-deposits)

The data for this plot comes from the quarterly bank financial data collected using the FDIC API. Then, in the Data Cleaning tab, we grouped the data by state, by bank, and by date meaning our data now showed the total assets, deposits, etc. that each bank in a given state held in a given quarter. This helped to shrink what was previously a massive dataset. However, that was still quite large. Therefore, that data file was added to `.gitignore`, however, you can see the code to create this file under `quarterly_data_cleaning.ipynb`. Running this notebook will allow you to see exactly what data we are using.

This plot went through a lot of variations. It began by included every state's total assets in five year windows with a slider to let the user move through the data. We then realize that five years was no where near enough time to see meaningful change so we expanded it to a decade long window. From there we realized that it would be better to just show all of the time at once, so the slider was scrapped. After doing some digging with the geo-spacial data, we found some interesting trends with the amount of money deposited in states you would not expect, such as South Dakota. In particular, we found that the biggest banks had tons of assets here. Quickly we realized this was worth exploring further so I split the data up by banks. However, it remained difficult to see how different the amounts of money was between states as you had to flip back and forth using the button. Finally, we switched to this subplot view which displays all of the states at once. The left column features the top three states by GDP while the right column features the three states we felt were most surprising in containing a ton of deposits despite being smaller states. They are all sorted vertically by GDP. 

After the poster fair, we decided to standardize the y-axes of all of the plots so that the differences in size between each state is more obvious. Now, the user is not asked to recognize the different y-axis maxes and instead they can easily see that, for example, California is half of the size of North Carolina. It also helps to conceptualize the size of the banks in the right column and see just how large JP Morgan, for example, is.

### Figure 5: Temporal trend of the total domestic deposits in the US for the past 3 decades
[View plot](index.qmd#sec-temporal-assets)

The data for this plot includes the total domestic deposits held by US banks for the past 3 decades, and is scraped using the FDIC API. Using `ggplot` in RStudio, the plot is formed by placing stacked bars, representing total assets for the year in the US. The data preparation included aggregating the dataframe and grouping the column names by the current year, in order to calculate the total assets. Next, the data is also categorised into the different bank classes, including Federal Reserve Members, Savings Banks, Mutual Savings Banks, etc. This is done so that the viewer is able to see the temporal trends not only in the total assets in the country for a given year, but to also see the trends within the different groups. 

### Figure 6: Disparity of the top 4 banks
[View plot](index.qmd#sec-top-banks)

The previous plot yields a result about the growth in assets over the years, but, in order to better understand the reason for this, the data frame is then aggregated by mean assets for the bank name and the year 2022, and then arranged in descending order to view the largest banks in the US for the most recent year, to create a dataframe called `filtered_desc`. The plot is a bar plot, with the mean assets for the year (calculated over quarterly data) on the y axis and the bank name on the x axis.

### Figure 7: The distribution of commercial banks in the US by the assets in possession
[View plot](index.qmd#sec-top-commercial)

Now, from the previous plot, top few banks are the ones that dominate the entire industry, so we adjust the data to take a more holistic approach towards viewing the banks, and then create a categorical variable for the asset class for the year 2022, divided by the mean US Dollars in assets. This variable has 4 categories. The number of banks in each category is plotted on the y axis with bars, and the x axis represents the bank names.

### Figure 8: Breakdown of top 5 banks, the next 125 banks, and all other banks
[View plot](index.qmd#sec-grouped-top-banks)

Only a small percentage of the banks in the previous plot belonged to the largest asset class with assets ranging from 10 million to 4 billion dollars, so we next decided to compare the top 5 banks, the next 125 banks, and all other banks in terms of their total assets, and also observe a temporal trend. The data is then aggregated again: creating another categorical variable for the asset group, and assigning them to banks based on the descending of their assets for a given year. The data is thereby prepared in such a way that the viewer can observe the disparity in how the top banks completely dominate the industry, and also view how this has not always been the case. 


### Figure 9: Top and Bottom 20 Histogram
[View plot](index.qmd#sec-state-bank-deposits)

This plot was built using the Altair library within python. As mentioned on the home page, this plot depicts a modified dataset where only banks that are present for at least 100 quarters are represented, including within the 'mean' column. The interactivity within the Altair library allows the user to click on a bar within the histogram and have that bank's equity capital ratio for each quarter since 1992 Q1 shown in the line graph below the histogram.

The intention with this plot was to get an understanding of whether banks that remain steady for an extended period of time fall close to the average EQR, and we find that this is not necessarily the case. However, it is more noteworthy that none of the four major banks that we have previously examined are present within the top and bottom 20 banks. In fact, as we will see in Figure 10, they fall remarkably close to the overall average. What we also note is that only 4 of the top 20 banks in this subset are from the three states we noted earlier (NC, OH, SD), with one being from North Carolina, and the remaining three being headquartered in Ohio. Additionally, 3 of the top 20 banks in terms of average equity capital ratio are from California, and two are from Michigan.

We experimented with the entire dataset, but the data were so skewed in both directions that we ultimately chose to only represent banks that appeared for at least 100 quarters since 1992. Some banks that likely only made up a few quarters had an EQR of over 100, and some even had values below 0. Therefore, in order to gain more meaningful insights about the general range of equity capital ratio over the past 30 years, we chose this specific subset of the data for this linked plot.



### Figure 10: Top 4 banks EQR by quarter with overall average
[View plot](index.qmd#sec-quarters-line-graph)

<p>This plot was built using the Altair library within python. This plot separates the 4 major banks that we examine throughout this project, and compares them to the overage average. The overall average does include the four banks, but it will not be skewed by the data since there are over 4,000 unique FDIC-insured banks within our dataset, and each are weighed equally in terms of determining the average for each quarter since 1992. </p>



### Figure 11: Joint distribution of average assets owned and average EQR per year
[View plot](index.qmd#sec-eqr-and-assets)

This plot was built using the Plotly library within python. Inspiration for the design of the plot was taken from the ANLY 503 week 8 lecture slides, specifically the slide titled "Marginal plot-2." This plot does depict a small subset of our original data, as it contains only banks with an average total asset count of under 500,000. This was done for two reasons. The first is to achieve the goal of analyzing the distinction between the equity capital ratio of the top 4 banks and the smaller banks. The second reason is because it would be very difficult to interpret the heatmap with all banks, since the majority of banks have an average asset count of less than 500,000. Therefore, it would be impossible to see the separation between the top banks that far surpass 500,000 in average total assets, and the banks that do not.


### Figure 12: Bubble plot of equity capital and equity capital ratio by year
[View plot](index.qmd#sec-bubble-plot)

This plot was built using the Plotly library within python. Inspiration for the design of the plot was taken from the ANLY 503 week 8 lecture slides, specifically the slide titled "animation and sliders." Inspiration was also drawn from lab-4.1, which explored various designs for time series bubble plots.

This plot contains a subset of the full dataset, as it explores only Q4 values from 1992, 2002, 2012, and 2022. Therefore, there are no averages taken for banks; these are the equity capital and equity capital ratio values for that specific quarter. We also filtered the dataset so it only included banks with a non-negative equity capital ratio, and an equity capital value less than or equal to 20,000,000. This is for the same reasons as illustrated in Figure 11. Essentially, we wanted to focus in on the smaller banks, since we already examined the equity capital ratio of the four large banks. Moreover, in an effort to make the plot fit on the page and look asthetically pleasing, we wanted to remove outliers and keep a filter where a large percentage of the data is still present, but the dispersion is not too drastic.