# to render `cd` to the code directoy and run `quarto render` (just those 2 commands)

project:
  type: website
  output-dir: ../../

website:
  title: Where is Your Money, and Why?
  search: false
  favicon: images/img/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home       
      - href: docs/methods.qmd
        text: Methods              
      - href: docs/data.qmd
        text: Data
      - href: docs/authors.qmd
        text: Authors        
  page-footer:
    left: |
      A project by [Group 4](docs/authors.qmd) <br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})


format:
  html:
    theme:
      - sandstone
      - custom.scss

bibliography: references.bib
csl: nature.csl
